### ISSUE TITLE
question about the PC TOOL 

### ISSUE THREAD

**Issue by kevin789654tw** [HimaxWiseEyePlus/WE_I_Plus_User_Examples#6]
Dear Kris：

Hi, my name is Kevin.  I've a question in using WE-I (DSI_6537), which is I can't show detect results by the PC TOOL. It doesn't have any responds. I like to know which step I got wrong. This is the step I did on my linux ubuntu 20.04. Thank you.

-->
1. Download and install FT4222 Linux driver
    (https://www.ftdichip.com/Support/SoftwareExamples/libft4222-linux-1.4.4.9.tg z)

2. cd into "libft4222-linux-1.4.4.9"
3. tar xfvz libft4222-1.4.4.9.tgz
4. sudo ./install4222.sh

5. cd into "examples"
6. cc get-version.c -lft4222 -Wl,-rpath,/usr/local/lib
7. sudo ./a.out
    (Terminal show --> Chip version: 42220400, LibFT4222 version: 01040409)

8. cd /etc/udev/rules.d/
9. vim 99-ftdi.rules
   ( What I type : # FTDI's ft4222 USB-I2C AdapterSUBSYSTEM=="usb", ATTRS{idVendor}=="0403", ATTRS{idProduct}=="601c", GROUP="plugdev", MODE="0666" )

10. cd into "my folder" (where I put the PC TOOL)
11. chmod 777 PC_TOOL_Linux
12. Then I click PC_TOOL_Linux, and click Recv

Best Regards
Kevin LIn
博誠電子股份有限公司 
Brocere Electronics Co. Ltd. 
http://www.brocere.com

**Comment by kris-himax** [comment]
@kevin789654tw hi
1. Check your 99-ftdi.rules. Because you say that you type ( # FTDI's ft4222 USB-I2C AdapterSUBSYSTEM=="usb", ATTRS{idVendor}=="0403", ATTRS{idProduct}=="601c", GROUP="plugdev", MODE="0666" ), it may be commented out the  rule. You should type two lines which like the below example. 
 #FTDI's ft4222 USB-I2C Adapter
SUBSYSTEM=="usb", ATTRS{idVendor}=="0403", ATTRS{idProduct}=="601c", GROUP="plugdev", MODE="0666"

2.
Make sure that you had sent the image by SPI at your WE-I code.

**Comment by kevin789654tw** [comment]
Thank you for your reply and answer. 
It helps me a lot, and solved the problem!!
